version: '1.0.0'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/embarca-project
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
volumes:
  dbdata: